### ISSUE TITLE
ConnectWiseEndpoint._make_request() argument "as_json" not implemented

### ISSUE THREAD

**Issue by EMoonArchiTech** [HealthITAU/pyconnectwise#8]
Hi all, while digging around in this cool piece of software you've made, I found an unimplemented argument in the _make_request() function. specifically, "as_json" is mentioned in the docstring but from what I can see does not seem to be implemented in the function itself. 

I also looked in the requests.api module and it does not appear to be present as a parameter there either. However, I have not been able to test this myself so apologies if this is onerous.

Should this be implemented in code or removed from the docs?

https://github.com/HealthITAU/pyconnectwise/blob/1b4ae5462c6fdde42096e10f783614877cdb4539/src/pyconnectwise/endpoints/base/connectwise_endpoint.py#L130

**Comment by Yoshify** [comment]
Thanks for raising this - this was a legacy parameter that has since been removed as we didn't see much use for it internally, but documentation hasn't been updated. As this project is still in pre-release phase no documentation has been finalized, there'll be a sweep done once we're at a state where we're ready to call it finished.

You're welcome to submit a PR for this if you'd like, otherwise I'll be tracking it for update in an upcoming release.

Cheers!

**Comment by EMoonArchiTech** [comment]
> You're welcome to submit a PR for this if you'd like, otherwise I'll be tracking it for update in an upcoming release.

Done! Hopefully no issues :) I usually just commit to my own repo's so not super familiar with pull request etiquette.

**Comment by Yoshify** [comment]
All looked good, thanks for the help!

Closing this now.
